esphome:
  name: ai-camera
  friendly_name: AI Camera

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xxxxxxxxxxxx"
    password: "xxxxxxxxx"

captive_portal:
# I2C bus for the camera
i2c:
  - id: cam_i2c
    sda: GPIO8
    scl: GPIO9

# Optional encoder: improves stream handling
camera_encoder:
  type: esp32_camera
  quality: 70            # 0–100; 70 is a good balance
  buffer_size: 2097152   # 2MB buffer

# --- CAMERA ---------------------------------------------------
esp32_camera:
  id: dfrobot_cam
  name: "DFRobot AI Cam"

  external_clock:
    pin: GPIO5
    frequency: 20MHz

  i2c_id: cam_i2c

  data_pins: [GPIO16, GPIO18, GPIO21, GPIO17, GPIO14, GPIO7, GPIO6, GPIO4]
  vsync_pin: GPIO1
  href_pin: GPIO2
  pixel_clock_pin: GPIO15

  # Image / frame settings
  resolution: 1024x768
  jpeg_quality: 10
  max_framerate: 15fps
  idle_framerate: 1fps
  frame_buffer_count: 2
  frame_buffer_location: PSRAM

  brightness: 1
  contrast: 1
  saturation: 0
  vertical_flip: true
  horizontal_mirror: false

  # Exposure settings
  aec_mode: auto
  aec2: true
  ae_level: 0

  # Gain / sensitivity settings
  agc_mode: auto
  agc_gain_ceiling: 64x   # higher = more sensitive, more noise

  # White balance
  wb_mode: auto

binary_sensor:
  - platform: status
    name: "AI Cam Status"

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
